name: rgtc
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - pillow
  - tqdm
  - matplotlib
  - scipy
  - pip:
      - torch>=2.1
      - torchvision>=0.16
      - timm==0.9.12
      - fvcore
      - einops
      - pyyaml
      - requests
      - transformers
      - lpips
      - pytorch-msssim
